GET http://localhost:3000/api/tasks/search?priority=low,medium

###
GET http://localhost:3000/api/tasks/18

###

POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Tarefa de teste",
    "priority": "urgent",
    "dueDate": "2026-05-05",
    "description":"Uma tarefa criada para teste da rota post"
}

###

PUT http://localhost:3000/api/tasks/state/2
Content-Type: application/json

{
    "state" : "completed"
}

###
PUT http://localhost:3000/api/tasks/21
Content-Type: application/json

{
    "title":"Nova tarefa editada",
    "priority":"urgent",
    "description":"nova descricao atualizada",
    "dueDate":"2026-05-02"
}

###

DELETE http://localhost:3000/api/tasks/2